# Generated by Django 4.0.3 on 2022-03-11 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='date_naissance',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='eleve',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='prenom',
        ),
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
