# Generated by Django 4.0.3 on 2022-03-13 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_remove_lesson_eleve_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professeur',
            old_name='date_naissance',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='professeur',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='professeur',
            name='formation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
