# Generated by Django 4.0.3 on 2022-03-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_date_naissance_professeur_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='phone',
        ),
    ]
