# Generated by Django 4.0.3 on 2022-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_eleve_birth_date_remove_eleve_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='phone',
            field=models.CharField(default=132, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='phone',
            field=models.CharField(default=321356, max_length=255),
            preserve_default=False,
        ),
    ]
