# Generated by Django 4.0.3 on 2022-03-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_eleve_birth_date_eleve_phone_professeur_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='phone',
        ),
    ]
