# Generated by Django 4.0.3 on 2022-03-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.eleve')),
            ],
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
