# Generated by Django 4.0.3 on 2022-03-28 14:59

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_eleveimage_delete_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleveimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[dashboard.validators.validate_file_size]),
        ),
    ]
