# Generated by Django 4.0.3 on 2022-03-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.professeur')),
            ],
        ),
    ]
