# Generated by Django 4.0.3 on 2022-04-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_task_delete_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
