# Generated by Django 4.0.3 on 2022-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_meeting_student_alter_meeting_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='student',
            new_name='eleve',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='teacher',
            new_name='professeur',
        ),
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
