# Generated by Django 4.0.3 on 2022-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_rename_date_meeting_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
