# Generated by Django 4.0.3 on 2022-04-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_meeting_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.eleve'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.professeur'),
        ),
    ]
