# Generated by Django 4.0.3 on 2022-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Refused'), ('A', 'Accepted')], default='P', max_length=1),
        ),
    ]
