# Generated by Django 4.0.3 on 2022-04-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_meet_username_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='username_recipient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
