# Generated by Django 4.0.3 on 2022-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_review_rate_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='color',
        ),
        migrations.AddField(
            model_name='meet',
            name='meetingNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
