# Generated by Django 4.0.3 on 2022-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_meet_color_meet_meetingnumber_meet_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
