# Generated by Django 4.0.3 on 2022-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_professeur_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
