# Generated by Django 4.0.3 on 2022-05-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_comment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.professeur'),
            preserve_default=False,
        ),
    ]
