# Generated by Django 4.0.3 on 2022-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='linkedIn',
            field=models.CharField(default='linkedIn', max_length=255),
        ),
    ]
