# Generated by Django 4.0.3 on 2022-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_lessonelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='join_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
