# Generated by Django 4.0.3 on 2022-05-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_meet_join_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='join_url',
            new_name='join_URL',
        ),
    ]
