# Generated by Django 4.0.3 on 2022-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student'), ('TM', 'TaskManager')], default='S', max_length=2),
        ),
    ]
