# Generated by Django 4.0.3 on 2022-03-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_birth_date_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
