# Generated by Django 4.0.3 on 2022-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
