# Generated by Django 4.0.3 on 2022-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('core', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
