# Generated by Django 4.0.3 on 2022-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('core', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
