# Generated by Django 4.0.3 on 2022-03-28 14:59

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('core', '0011_remove_user_token_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images', validators=[dashboard.validators.validate_file_size]),
        ),
    ]
