# Generated by Django 4.0.3 on 2022-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_image'),
        ('core', '0013_alter_user_birth_date'),
    ]

    operations = [
    ]
