# Generated by Django 4.0.3 on 2022-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('core', '0014_merge_0012_user_image_0013_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
